### ISSUE TITLE
channel param is not used with Google API_KEY

### ISSUE THREAD

**Issue by lsharma-ridecell** [hzlmn/aiogmaps#17]
https://developers.google.com/maps/premium/apikey/directions-apikey

**Authentication using an API key (Premium Plan)**
By using an API key to authenticate your request, you can:
Manage all of your APIs in the Google Cloud Platform Console.
Access real-time usage data and 30 days of historical usage data in the Google Cloud Platform Console.
Add the channel parameter to requests so you can view more detailed usage reports.
View usage reports with more than 30 days of data in the Google Cloud Support Portal.

**Comment by jpoehnelt** [comment]
`channel` is ONLY for premium accounts(discontinued) and is not compatible with key based auth.

**Comment by hzlmn** [comment]
Hi, @lsharma-ridecell sorry for delay,  as @jpoehnelt told. Can your question be considered closed?

**Comment by lsharma-ridecell** [comment]
Yes, This can be considered as closed. 
How we can get a similar functionality like a channel with API_KEY?

**Comment by jpoehnelt** [comment]
Please file a feature request at https://issuetracker.google.com/issues/new?component=188853&template=787814.
